#!/bin/bash

#[ `which arm-none-eabi-gcc` ] && TOOLCHAIN_PREFIX="arm-none-eabi-" || TOOLCHAIN_PREFIX="arm-eabi-"
export TOOLCHAIN_PREFIX=arm-linux-gnueabihf-

if [ ! -f bin/nbgen ]; then
	gcc -std=c99 nbgen.c -o nbgen
fi

chmod +x yang
./nbgen os.nb
./yang -F RUU_signed.nbh -f os.nb -t 0x400 -s 64 -d PB8110000 -c 11111111 -v EDK2 -l WWE



